version: "3.7"

services:
  back:
    build:
      context: ./flask
      dockerfile: ../docker/dev.backend.Dockerfile    
    volumes:
      - .:/usr/src
    ports:
      - 5000:5000
    environment:
        FLASK_APP: ./run.py
        FLASK_DEBUG: "on"
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0