str_constraints = [
    "Each woman has a different tshirt.",
    "Each woman has a different name.",
    "Each woman has a different surname.",
    "Each woman has a different favourite pasta.",
    "Each woman has a different favourite wine.",
    "Each woman has a different age.",
    "The woman wearing the White shirt is next to the woman who likes Lombardian wines.",
    "Ms Miller is somewhere between Ms Davis and Ms Brown, in that order.",
    "The youngest woman is at the third position.",
    "The 45-year-old woman is somewhere to the right of the woman wearing the Red shirt.",
    "The woman who likes Chilean wines also likes Farfalle.",
    "At the first position is the woman that likes Argentine wines.",
    "Andrea is exactly to the right of the 35-year-old woman.",
    "The woman wearing the Blue shirt is somewhere between Ms Davis and Holly, in that order.",
    "Victoria is next to Leslie.",
    "The woman wearing the Red shirt is somewhere to the left of the woman who likes Australian wines.",
    "Ms Wilson is next to the 30-year-old woman.",
    "Leslie is exactly to the left of the 30-year-old woman.",
    "Holly is somewhere to the right of the woman wearing the Red shirt.",
    "Ms Brown is exactly to the left of Julie.",
    "The youngest woman likes Penne.",
    "Ms Wilson is wearing the White shirt.",
    "The woman who likes Lasagne is somewhere between the woman who likes Italian wines and the woman who likes Spaghetti, in that order."
    "At the second position is the woman wearing the Blue shirt.",
    "The 40-year-old woman likes Lasagne.",
    "Ms Lopes is at the fifth position.",
    "The woman that likes Australian wines is somewhere between Victoria and the woman who likes wines from Bordeaux, in that order.",
    "The woman wearing the Yellow shirt is exactly to the left of the 35-year-old woman.",
    # La reponse du solveur a une contrainte de plus donc j'ai temporairement ajouté MISSING
    "MISSING",
]
