tshirts = ["blue", "green", "red", "white", "yellow"]
names = ["andrea", "holly", "julie", "leslie", "victoria"]
surnames = ["brown", "davis", "lopes", "miller", "wilson"]
pastas = ["farfalle", "lasagne", "penne", "spaghetti", "ravioli"]
wines = ["australian", "argentine", "chilean", "french", "italian"]
ages = [30, 35, 40, 45, 50]
